version: '2'
services:
  repo5-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/repo5/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=repo5
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
